// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSimpleTop.h for the primary calling header

#ifndef VERILATED_VSIMPLETOP___024ROOT_H_
#define VERILATED_VSIMPLETOP___024ROOT_H_  // guard

#include "verilated.h"


class VSimpleTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VSimpleTop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_start,0,0);
        VL_OUT8(io_done,0,0);
        CData/*1:0*/ SimpleTop__DOT__state;
        CData/*3:0*/ SimpleTop__DOT__timer;
        CData/*0:0*/ SimpleTop__DOT__busyTable_0;
        CData/*0:0*/ SimpleTop__DOT__busyTable_1;
        CData/*0:0*/ SimpleTop__DOT__busyTable_2;
        CData/*0:0*/ SimpleTop__DOT__busyTable_3;
        CData/*0:0*/ SimpleTop__DOT__busyTable_4;
        CData/*4:0*/ SimpleTop__DOT__nextIssueId;
        CData/*0:0*/ SimpleTop__DOT__activeReg;
        CData/*0:0*/ SimpleTop__DOT__activeReg_1;
        CData/*0:0*/ SimpleTop__DOT__activeReg_2;
        CData/*0:0*/ SimpleTop__DOT__activeReg_3;
        CData/*0:0*/ SimpleTop__DOT__activeReg_4;
        CData/*2:0*/ SimpleTop__DOT__pcReg;
        CData/*0:0*/ SimpleTop__DOT___GEN;
        CData/*0:0*/ SimpleTop__DOT__stall;
        CData/*0:0*/ SimpleTop__DOT__intents_0_acquire;
        CData/*0:0*/ SimpleTop__DOT___GEN_0;
        CData/*0:0*/ SimpleTop__DOT__intents_0_release;
        CData/*0:0*/ SimpleTop__DOT__intents_0_reg;
        CData/*0:0*/ SimpleTop__DOT___GEN_2;
        CData/*0:0*/ SimpleTop__DOT__doneWire;
        CData/*2:0*/ SimpleTop__DOT__pcReg_1;
        CData/*0:0*/ SimpleTop__DOT___GEN_3;
        CData/*0:0*/ SimpleTop__DOT___stall_T_7;
        CData/*0:0*/ SimpleTop__DOT__intents_1_acquire;
        CData/*0:0*/ SimpleTop__DOT___GEN_4;
        CData/*0:0*/ SimpleTop__DOT__intents_1_release;
        CData/*0:0*/ SimpleTop__DOT__intents_1_reg;
        CData/*0:0*/ SimpleTop__DOT___GEN_6;
        CData/*0:0*/ SimpleTop__DOT__doneWire_1;
        CData/*2:0*/ SimpleTop__DOT__pcReg_2;
        CData/*0:0*/ SimpleTop__DOT___GEN_7;
        CData/*0:0*/ SimpleTop__DOT__stall_6;
        CData/*0:0*/ SimpleTop__DOT__intents_2_acquire;
        CData/*0:0*/ SimpleTop__DOT___GEN_9;
        CData/*0:0*/ SimpleTop__DOT__intents_2_release;
        CData/*0:0*/ SimpleTop__DOT___GEN_12;
        CData/*0:0*/ SimpleTop__DOT__doneWire_2;
        CData/*2:0*/ SimpleTop__DOT__pcReg_3;
        CData/*0:0*/ SimpleTop__DOT___GEN_13;
        CData/*0:0*/ SimpleTop__DOT___stall_T_15;
        CData/*0:0*/ SimpleTop__DOT__intents_3_acquire;
        CData/*0:0*/ SimpleTop__DOT___GEN_15;
        CData/*0:0*/ SimpleTop__DOT__io_1_req;
        CData/*0:0*/ SimpleTop__DOT__io_1_isWr;
        CData/*0:0*/ SimpleTop__DOT___GEN_16;
        CData/*0:0*/ SimpleTop__DOT___GEN_17;
        CData/*0:0*/ SimpleTop__DOT__intents_3_release;
        CData/*0:0*/ SimpleTop__DOT___GEN_19;
        CData/*0:0*/ SimpleTop__DOT__doneWire_3;
        CData/*2:0*/ SimpleTop__DOT__pcReg_4;
        CData/*0:0*/ SimpleTop__DOT___GEN_20;
        CData/*0:0*/ SimpleTop__DOT___stall_T_19;
        CData/*0:0*/ SimpleTop__DOT__intents_4_acquire;
        CData/*0:0*/ SimpleTop__DOT___GEN_21;
        CData/*0:0*/ SimpleTop__DOT___GEN_22;
        CData/*0:0*/ SimpleTop__DOT__intents_4_release;
        CData/*0:0*/ SimpleTop__DOT__intents_4_reg;
        CData/*0:0*/ SimpleTop__DOT___GEN_24;
    };
    struct {
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_28;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_29;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_30;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_31;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_32;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_33;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_34;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_35;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_36;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_37;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_38;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___stall_hazard_T_146;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_39;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_40;
        CData/*2:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_41;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__stall_7;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_42;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_43;
        CData/*4:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_44;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__stall_8;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_45;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_46;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_47;
        CData/*5:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_48;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__stall_10;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_49;
        CData/*3:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_50;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_51;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_52;
        CData/*6:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_53;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__stall_13;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_54;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__stall_14;
        CData/*7:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_56;
        CData/*7:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_57;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_59;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk3__DOT___GEN_60;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk4__DOT___GEN_61;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk4__DOT___GEN_62;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk5__DOT___GEN_63;
        CData/*0:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk5__DOT___GEN_64;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_0;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_1;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_2;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_3;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_4;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_5;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_6;
        CData/*0:0*/ SimpleTop__DOT____VdfgRegularize_h78706270_0_7;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        SData/*8:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_55;
        VL_OUT(io_r1,31,0);
        VL_OUT(io_r2,31,0);
        VL_OUT(io_r3,31,0);
        VL_OUT(io_r4,31,0);
        IData/*31:0*/ SimpleTop__DOT__phyRegs_1;
        IData/*31:0*/ SimpleTop__DOT__phyRegs_2;
        IData/*31:0*/ SimpleTop__DOT__phyRegs_3;
        IData/*31:0*/ SimpleTop__DOT__phyRegs_4;
        IData/*31:0*/ SimpleTop__DOT__mem_0;
        IData/*31:0*/ SimpleTop__DOT__mem_1;
        IData/*31:0*/ SimpleTop__DOT__mem_2;
        IData/*31:0*/ SimpleTop__DOT__mem_3;
    };
    struct {
        IData/*31:0*/ SimpleTop__DOT__mem_4;
        IData/*31:0*/ SimpleTop__DOT__mem_5;
        IData/*31:0*/ SimpleTop__DOT__mem_6;
        IData/*31:0*/ SimpleTop__DOT__mem_7;
        IData/*31:0*/ SimpleTop__DOT__mem_8;
        IData/*31:0*/ SimpleTop__DOT__mem_9;
        IData/*31:0*/ SimpleTop__DOT__mem_10;
        IData/*31:0*/ SimpleTop__DOT__mem_11;
        IData/*31:0*/ SimpleTop__DOT__mem_12;
        IData/*31:0*/ SimpleTop__DOT__mem_13;
        IData/*31:0*/ SimpleTop__DOT__mem_14;
        IData/*31:0*/ SimpleTop__DOT__mem_15;
        IData/*31:0*/ SimpleTop__DOT__mem_16;
        IData/*31:0*/ SimpleTop__DOT__mem_17;
        IData/*31:0*/ SimpleTop__DOT__mem_18;
        IData/*31:0*/ SimpleTop__DOT__mem_19;
        IData/*31:0*/ SimpleTop__DOT__mem_20;
        IData/*31:0*/ SimpleTop__DOT__mem_21;
        IData/*31:0*/ SimpleTop__DOT__mem_22;
        IData/*31:0*/ SimpleTop__DOT__mem_23;
        IData/*31:0*/ SimpleTop__DOT__mem_24;
        IData/*31:0*/ SimpleTop__DOT__mem_25;
        IData/*31:0*/ SimpleTop__DOT__mem_26;
        IData/*31:0*/ SimpleTop__DOT__mem_27;
        IData/*31:0*/ SimpleTop__DOT__mem_28;
        IData/*31:0*/ SimpleTop__DOT__mem_29;
        IData/*31:0*/ SimpleTop__DOT__mem_30;
        IData/*31:0*/ SimpleTop__DOT__mem_31;
        IData/*31:0*/ SimpleTop__DOT__mem_32;
        IData/*31:0*/ SimpleTop__DOT__mem_33;
        IData/*31:0*/ SimpleTop__DOT__mem_34;
        IData/*31:0*/ SimpleTop__DOT__mem_35;
        IData/*31:0*/ SimpleTop__DOT__mem_36;
        IData/*31:0*/ SimpleTop__DOT__mem_37;
        IData/*31:0*/ SimpleTop__DOT__mem_38;
        IData/*31:0*/ SimpleTop__DOT__mem_39;
        IData/*31:0*/ SimpleTop__DOT__mem_40;
        IData/*31:0*/ SimpleTop__DOT__mem_41;
        IData/*31:0*/ SimpleTop__DOT__mem_42;
        IData/*31:0*/ SimpleTop__DOT__mem_43;
        IData/*31:0*/ SimpleTop__DOT__mem_44;
        IData/*31:0*/ SimpleTop__DOT__mem_45;
        IData/*31:0*/ SimpleTop__DOT__mem_46;
        IData/*31:0*/ SimpleTop__DOT__mem_47;
        IData/*31:0*/ SimpleTop__DOT__mem_48;
        IData/*31:0*/ SimpleTop__DOT__mem_49;
        IData/*31:0*/ SimpleTop__DOT__mem_50;
        IData/*31:0*/ SimpleTop__DOT__mem_51;
        IData/*31:0*/ SimpleTop__DOT__mem_52;
        IData/*31:0*/ SimpleTop__DOT__mem_53;
        IData/*31:0*/ SimpleTop__DOT__mem_54;
        IData/*31:0*/ SimpleTop__DOT__mem_55;
        IData/*31:0*/ SimpleTop__DOT__mem_56;
        IData/*31:0*/ SimpleTop__DOT__mem_57;
        IData/*31:0*/ SimpleTop__DOT__mem_58;
        IData/*31:0*/ SimpleTop__DOT__mem_59;
        IData/*31:0*/ SimpleTop__DOT__mem_60;
        IData/*31:0*/ SimpleTop__DOT__mem_61;
        IData/*31:0*/ SimpleTop__DOT__mem_62;
        IData/*31:0*/ SimpleTop__DOT__mem_63;
        IData/*31:0*/ SimpleTop__DOT__mem_64;
        IData/*31:0*/ SimpleTop__DOT__mem_65;
        IData/*31:0*/ SimpleTop__DOT__mem_66;
        IData/*31:0*/ SimpleTop__DOT__mem_67;
    };
    struct {
        IData/*31:0*/ SimpleTop__DOT__mem_68;
        IData/*31:0*/ SimpleTop__DOT__mem_69;
        IData/*31:0*/ SimpleTop__DOT__mem_70;
        IData/*31:0*/ SimpleTop__DOT__mem_71;
        IData/*31:0*/ SimpleTop__DOT__mem_72;
        IData/*31:0*/ SimpleTop__DOT__mem_73;
        IData/*31:0*/ SimpleTop__DOT__mem_74;
        IData/*31:0*/ SimpleTop__DOT__mem_75;
        IData/*31:0*/ SimpleTop__DOT__mem_76;
        IData/*31:0*/ SimpleTop__DOT__mem_77;
        IData/*31:0*/ SimpleTop__DOT__mem_78;
        IData/*31:0*/ SimpleTop__DOT__mem_79;
        IData/*31:0*/ SimpleTop__DOT__mem_80;
        IData/*31:0*/ SimpleTop__DOT__mem_81;
        IData/*31:0*/ SimpleTop__DOT__mem_82;
        IData/*31:0*/ SimpleTop__DOT__mem_83;
        IData/*31:0*/ SimpleTop__DOT__mem_84;
        IData/*31:0*/ SimpleTop__DOT__mem_85;
        IData/*31:0*/ SimpleTop__DOT__mem_86;
        IData/*31:0*/ SimpleTop__DOT__mem_87;
        IData/*31:0*/ SimpleTop__DOT__mem_88;
        IData/*31:0*/ SimpleTop__DOT__mem_89;
        IData/*31:0*/ SimpleTop__DOT__mem_90;
        IData/*31:0*/ SimpleTop__DOT__mem_91;
        IData/*31:0*/ SimpleTop__DOT__mem_92;
        IData/*31:0*/ SimpleTop__DOT__mem_93;
        IData/*31:0*/ SimpleTop__DOT__mem_94;
        IData/*31:0*/ SimpleTop__DOT__mem_95;
        IData/*31:0*/ SimpleTop__DOT__mem_96;
        IData/*31:0*/ SimpleTop__DOT__mem_97;
        IData/*31:0*/ SimpleTop__DOT__mem_98;
        IData/*31:0*/ SimpleTop__DOT__mem_99;
        IData/*31:0*/ SimpleTop__DOT__mem_100;
        IData/*31:0*/ SimpleTop__DOT__mem_101;
        IData/*31:0*/ SimpleTop__DOT__mem_102;
        IData/*31:0*/ SimpleTop__DOT__mem_103;
        IData/*31:0*/ SimpleTop__DOT__mem_104;
        IData/*31:0*/ SimpleTop__DOT__mem_105;
        IData/*31:0*/ SimpleTop__DOT__mem_106;
        IData/*31:0*/ SimpleTop__DOT__mem_107;
        IData/*31:0*/ SimpleTop__DOT__mem_108;
        IData/*31:0*/ SimpleTop__DOT__mem_109;
        IData/*31:0*/ SimpleTop__DOT__mem_110;
        IData/*31:0*/ SimpleTop__DOT__mem_111;
        IData/*31:0*/ SimpleTop__DOT__mem_112;
        IData/*31:0*/ SimpleTop__DOT__mem_113;
        IData/*31:0*/ SimpleTop__DOT__mem_114;
        IData/*31:0*/ SimpleTop__DOT__mem_115;
        IData/*31:0*/ SimpleTop__DOT__mem_116;
        IData/*31:0*/ SimpleTop__DOT__mem_117;
        IData/*31:0*/ SimpleTop__DOT__mem_118;
        IData/*31:0*/ SimpleTop__DOT__mem_119;
        IData/*31:0*/ SimpleTop__DOT__mem_120;
        IData/*31:0*/ SimpleTop__DOT__mem_121;
        IData/*31:0*/ SimpleTop__DOT__mem_122;
        IData/*31:0*/ SimpleTop__DOT__mem_123;
        IData/*31:0*/ SimpleTop__DOT__mem_124;
        IData/*31:0*/ SimpleTop__DOT__mem_125;
        IData/*31:0*/ SimpleTop__DOT__mem_126;
        IData/*31:0*/ SimpleTop__DOT__mem_127;
        IData/*31:0*/ SimpleTop__DOT__rdataBuffer;
        IData/*31:0*/ SimpleTop__DOT__addrLatch;
        IData/*31:0*/ SimpleTop__DOT__res;
        IData/*31:0*/ SimpleTop__DOT__op1_1;
    };
    struct {
        IData/*31:0*/ SimpleTop__DOT__res_1;
        IData/*31:0*/ SimpleTop__DOT__addrVal;
        IData/*31:0*/ SimpleTop__DOT__dataVal;
        IData/*31:0*/ SimpleTop__DOT__addrVal_1;
        IData/*31:0*/ SimpleTop__DOT__memData;
        IData/*31:0*/ SimpleTop__DOT__io_1_addr;
        IData/*31:0*/ SimpleTop__DOT__op1_2;
        IData/*31:0*/ SimpleTop__DOT__op2;
        IData/*31:0*/ SimpleTop__DOT__res_2;
        IData/*31:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT__io_1_wdata;
        IData/*31:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_58;
        VlWide<128>/*4095:0*/ SimpleTop__DOT__unnamedblk1__DOT__unnamedblk6__DOT___GEN_65;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    VSimpleTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VSimpleTop___024root(VSimpleTop__Syms* symsp, const char* v__name);
    ~VSimpleTop___024root();
    VL_UNCOPYABLE(VSimpleTop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
